config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :phones,  only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create, :show]
  end
  resources :bookings, except: [:new, :create, :show]

  namespace :my do
    resources :phones, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :phone
  belongs_to :user
  validates :start_booking, :user, :phone, :end_booking, presence: true
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :state, presence: true, inclusion: { in: ['Correct', 'Bon etat', 'Tres bon etat'] }
  validates :brand, presence: true, inclusion: { in: ['Apple', 'Samsung', 'Huawei', 'Xiaomi'] }
  validates :model, presence: true, inclusion: { in: ['Iphone X', 'Iphone 11', 'Iphone 12', 'Galaxy', 'Note', 'Star', 'P10', 'Iphone XR', 'Iphone 8', 'Iphone SE', 'Iphone 12 pro', 'Iphone XS max', 'P20', 'P30'] }
  validates :user, :start_dispo, :end_dispo, :model, :description, presence: true
  validates :price, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :phones, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def new
    @booking = Booking.new
    @phone = Phone.find(params[:phone_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @phone = Phone.find(params[:phone_id])
    @booking.phone_id = @phone.id
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to phone_booking_path(@phone, @booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @bookings = Booking.where(user: current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_booking, :end_booking)
  end
end

app/controllers/my/phones_controller.rb
class My::PhonesController < ApplicationController
  def index
    @phones = current_user.phones
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @phone = Phone.new
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        brand @@ :query \
        OR model @@ :query \
      "
      @phones = Phone.where(sql_query, query: "%#{params[:query]}%")
    else
      @phones = Phone.all
    end
  end

  def show

    @phone = Phone.find(params[:id])

    # collecting phones to provide Previous & Next

    # links, logic is in place to work in situations

    # where phones have the same last and/or

    # first names; login is unique

    @all_phones_array = Phone.all

    @curr_phones_index = @all_phones_array.index(@phone)
    # this defines our starting point
    # from which to base the Previous and Next links

    @previous_phone = @all_phones_array[@curr_phones_index - 1]

    @next_phone = @all_phones_array[@curr_phones_index + 1]

    @first_phones_id = @all_phones_array.first

    @last_phones_id = @all_phones_array.last
  end

  def new
    @phone = Phone.new
  end

  def create
    @phone = Phone.new(phone_params)
    @phone.user_id = current_user.id
    if @phone.save
      redirect_to my_phones_path
    else
      render :new
    end
  end

  private

  def phone_params
    params.require(:phone).permit(:start_dispo, :end_dispo, :brand, :model, :price, :address, :description, :photo, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <%= simple_form_for [ @phone, @booking ] do |f| %>
    <%= f.input :start_booking, html5: true %>
    <%= f.input :end_booking, html5: true %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<%= render partial: 'form' %>

app/views/bookings/index.html.erb
<h1 class="container mt-4">Mes réservations</h1>
<div class="reservation container border mt-4 p-3 rounded">
  <% @bookings.each do |booking| %>
    <%= link_to phone_path(booking.phone.id, booking.id) do %>
      <h2> <strong> <%= booking.phone.brand %> - <%= booking.phone.model %></strong></h2>
      <h3 class="EDIT">
        <%= link_to "Modifier ma location", edit_booking_path(booking) %>
        <%= link_to "Annuler la location",
            booking,
            method: :delete,
            data: { confirm: "Êtes vous sur de vouloir annuler la commande ? ( Si l'annulation se fait après envoie du téléphone, vous serez quand même facturé l'équivalent d'une journée de location)" } %>
      </h3>
    <% end %>
    <p> Vous avez réservé un <strong><%= booking.phone.model %></strong>  du <%= booking.start_booking %> au <%= booking.end_booking %>. </p>
  <% end %>
</div>

app/views/bookings/new.html.erb
 <!--   <div class="overlay"></div> -->
   <!--  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
      <source src="https://dm0qx8t0i9gc9.cloudfront.net/watermarks/video/Vd3bj2jPe/videoblocks-closeup-blonde-girl-using-smartphone-in-nightclub-portrait-of-smiling-female-person-holding-phone-on-neon-lights-background-cheerful-woman-making-video-on-mobile-phone-under-confetti-at-party_rkbha6dod__e3865c503db32951cc97e991da340d8c__P360.mp4">
    </video> -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.giphy.com/media/ToMjGpJ4jULsUli8yxW/giphy.gif); zoom-out:1.5;">
  <div class="container h-200">
    <div class="d-flex h-50 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-4">BIENVENUE SUR LA PAGE DE RESERVATION</h1>
        <p class="lead mb-0">
          Plus qu'une étape pour louer votre téléphone
        </p>
        <div class="container">
          <div class="f p-4 m-5 align-self-center">
            <div class="w-100 h-0 text-white">
              <%= simple_form_for [ @phone, @booking ] do |f| %>
              <%= f.input :start_booking, html5: true, label:'Début de réservation' %>
              <%= f.input :end_booking, html5: true, label:'Fin de réservation'%>
              <%= f.submit "Reserver", class: "btn btn-primary mt-3"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <!-- <div class="logo">
      <h4>BATMOBILE</h4>
    </div> -->


     <!--  <form action="/phones" accept-charset="UTF-8" method="get">
        <input type="text" name="brand" id="brand" class="form-control mb-3" placeholder="Marque">
        <select name="model" id="model" class="form-control" placeholder="Modèle"><option value="Modèle">Modèle</option>
<option value="Iphone X">Iphone X</option>
<option value="Iphone 11">Iphone 11</option>
<option value="Iphone 12">Iphone 12</option>
<option value="Galaxy">Galaxy</option>
<option value="Note">Note</option>
<option value="Star">Star</option>
<option value="P10">P10</option></select>
        <input type="submit" name="commit" value="Rechercher" class="btn btn-primary mt-3" data-disable-with="Rechercher">
</form> -->
<!--
<section class="my-2">
  <div class="container h-100">
      <div class="d-flex h-100 text-center align-items-center">
         <div class="col-md-4 col-lg-12">
            <h2 class="mb-3">RESERVATION</h2>
            <form class="needs-validation" novalidate="">
              <div class="row g-3">
                <div class="col-sm-6">
                  <label for="firstName" class="form-label">Prénom</label>
                  <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Prénoms
                  </div>
                </div>

                <div class="col-sm-6">
                  <label for="lastName" class="form-label">Nom</label>
                  <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Nom de famille
                  </div>
                </div>

                <div class="col-12">
                  <label for="username" class="form-label">Identifiant</label>
                  <div class="input-group has-validation">
                    <span class="input-group-text">@</span>
                    <input type="text" class="form-control" id="username" placeholder="Username" required="">
                  <div class="invalid-feedback">
                      Votre identifiant est recquis.
                    </div>
                  </div>
                </div>

                <div class="col-12">
                  <label for="email" class="form-label">Mèl <span class="text-muted">(Obligatoire)</span></label>
                  <input type="email" class="form-control" id="email" placeholder="you@example.com">
                  <div class="invalid-feedback">
                    Pourriez-vous avoir l'obligeance d'écrire un Mèl adéquate.
                  </div>
                </div>

                <div class="col-12">
                  <label for="address" class="form-label">Adresse de livraison</label>
                  <input type="text" class="form-control" id="address" placeholder="3 rue du doigt" required="">
                  <div class="invalid-feedback">
                    Veuillez avoir l'amabilité de bien mettre ici l'adresse de livraison de votre téléphone de PROLO!
                  </div>
                </div>

                <div class="col-md-4">
                  <label for="address" class="form-label">Produit sélectionné</label>
                  <input type="text" class="form-control" id="address" placeholder="Apple-Iphone-10-S gris" required="">
                  <div class="invalid-feedback">
                    Veuillez avoir l'amabilité de bien mettre ici votre type de téléphone de PROLO!
                  </div>
                </div>

                <div class="col-md-4">
                  <label for="state" class="form-label">Date de début de location</label>
                  <input class="datepicker" data-date-format="mm/dd/yyyy">
                </div>

                <div class="col-md-4">
                  <label for="state" class="form-label">Date de fin de location</label>
                  <input class="datepicker" data-date-format="mm/dd/yyyy">
                </div>


              </div>

              <hr class="my-4">

              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="same-address">
                <label class="form-check-label" for="same-address">L'adresse de livraison est la même que l'adresse de facturation</label>
              </div>

              <hr class="my-4">

              <h4 class="mb-3">Paiement</h4>

              <div class="my-3">
                <div class="form-check">
                  <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked="" required="">
                  <label class="form-check-label" for="credit">Carte de crédit</label>
                </div>

                <div class="form-check">
                  <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                  <label class="form-check-label" for="paypal">PayPal</label>
                </div>
              </div>

              <div class="row gy-3">
                <div class="col-md-6">
                  <label for="cc-name" class="form-label">Nom sur la carte</label>
                  <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                  <small class="text-muted">Full name as displayed on card</small>
                  <div class="invalid-feedback">
                    Nom du propriétaire de la carte
                  </div>
                </div>

                <div class="col-md-6">
                  <label for="cc-number" class="form-label">Numéro de carte</label>
                  <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                  <div class="invalid-feedback">
                    numéro de carte
                  </div>
                </div>

                <div class="col-md-3">
                  <label for="cc-expiration" class="form-label">Expiration</label>
                  <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                  <div class="invalid-feedback">
                    date d'expiration
                  </div>
                </div>

                <div class="col-md-3">
                  <label for="cc-cvv" class="form-label">CVV</label>
                  <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                  <div class="invalid-feedback">
                    code de sécurité
                  </div>
                </div>
              </div>

              <hr class="my-4">

              <button class="w-100 btn btn-primary btn-lg" type="submit">Valider la réservation</button>
            </form>
          </div>

            </div>
       </div>
      </div>
    </div>
</section>
 -->

app/views/bookings/show.html.erb
<div class="jumbotron text-center">
  <h1 class="display-3">Merci pour votre commande <%= current_user.username %></h1>
  <p class="lead"><strong>Votre téléphone</strong> sera bientôt livré</p>
  <hr>
  <p>
   Un problème? <a class= 'contact' href="">Contactez-nous</a>
  </p>
  <p>
   <%= link_to 'Voir mes réservations', bookings_path, class: "btn btn-primary"%>
   </p>
  <p class="lead">
    <%= link_to 'retourner au menu', root_path, class:"btn btn-primary" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batmobile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dekexda28/image/upload/v1621349597/bat_logo_bt62bg.png" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link py-3" %>
            </li>
            <li class="nav-item">
              <%= link_to "Se connecter", new_user_session_path, class: "nav-link py-3" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "#{current_user.username}", "#", class: "nav-link py-3" %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= image_tag "https://res.cloudinary.com/dekexda28/image/upload/v1621539379/user_cooewh.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Mes reservations", bookings_path, class: "dropdown-item" %>
                <%= link_to "Mes appareils", my_phones_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/my/phones/index.html.erb
<div class="background">
  <div class= "container text-center mt-4">
    <h1>Vos téléphones</h1>
    <%= link_to 'Ajouter un téléphone', new_phone_path, class:'btn btn-primary mt-3' %>
    <div class="card-list mt-3">
        <% @phones.each do |phone| %>
          <%= link_to phone_path(phone) do %>
            <div class="card-trip card-border">
              <% if phone.photo.present? %>
                <%= cl_image_tag phone.photo.key %>
              <% end %>
              <div class="card-trip-infos">
              <div>
                <h2><%= phone.model %></h2>
                <p>Du <%= phone.start_dispo %> au  <%= phone.end_dispo %> </p>
              </div>
                <h3 class="card-trip-pricing"><%= phone.price %>€/jours</h3>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dekexda28/image/upload/v1621351558/banner_gzz6ec.jpg);">
  <div class="container">
    <div class="logo">
      <h1>BATMOBILE</h1>
    </div>
    <h2> Tu as besoin rapidement d'un téléphone ? <strong>Loues-le !</strong>!</h2>
    <p>Choisis le modèle ou la marque recherchée.</p>

    <div class="f p-4 mt-4 text-center">
      <%= form_tag phones_path, method: :get do %>
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Modèle/marque"%>
          <%= submit_tag "Rechercher", class: "mt-3 p-2 btn btn-primary bouton"%>
      <% end %>
    </div>
  </div>
</div>

app/views/phones/index.html.erb
<div class="background">
  <div class= "container">
    <div class="mt-3 text-center text-black">
      <h1>Louer un téléphone</h1>
      <%= form_tag phones_path, method: :get do %>
        <div class="search-container">
          <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Modèle/marque"%>
          <%= submit_tag "Rechercher", class: "m-2 p-2 btn btn-primary bouton"%>
        </div>
      <% end %>
    </div>
    <div class="card-list">
        <% @phones.each do |phone| %>
          <%= link_to phone_path(phone) do %>
            <div class="card-trip card-border">
              <% if phone.photo.present? %>
                <%= cl_image_tag phone.photo.key%>
                <% end %>
              <div class="card-trip-infos">
              <div>
                <h2><%= phone.model %></h2>
                <p>Ce model est fait pour vous!</p>
              </div>
                <h3 class="card-trip-pricing"><%= phone.price %>€/jours</h3>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/phones/new.html.erb
<div class="container mt-4">

  <h1 class="text-center"> Créer un nouveau téléphone</h1>

  <%= simple_form_for @phone do |f|%>
    <%= f.input :brand, label:"La marque", collection: ['Apple', 'Samsung', 'Huawei', 'Xiaomi'] %>
    <%= f.input :model, label:"Le modèle" , collection: ['Iphone X', 'Iphone 11', 'Iphone 12', 'Galaxy', 'Note', 'Star', 'P10'] %>
    <%= f.input :start_dispo, html5: true, label: "Date de début de mise à diposition" %>
    <%= f.input :end_dispo, html5: true, label:"Date de fin de mise à diposition" %>
    <%= f.input :price, label:"Prix journalier (€/j)" %>
    <%= f.input :address, label:"Address/point relais (lieu de récupération de votre téléphone)" %>
    <%= f.input :state, label:'État', collection: ['Correct', 'Bon état', 'Très bon état'] %>
    <%= f.input :photo, as: :file %>
    <%= f.input :description, label:"Description" %>
    <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div>

app/views/phones/show.html.erb
<div class="container d-flex align-items-center">
  <% @phone.id == @first_phones_id ? @previous = @last_phones_id : @previous = @previous_phone %>
  <%= link_to @previous, class:'btn btn-primary arrow' do %>
    <p> < </p>
  <% end %>
  <div class="card-product">
    <div class="card-img">
      <% if @phone.photo.present? %>
        <%= cl_image_tag @phone.photo.key %>
      <% end %>
    </div>
    <div class="resume pt-4">
    <h2 class="desc p-3 mx-5 my-2"><%= @phone.model %></h2>
    <div class="desc p-3 mx-5 my-2">
      <p>Marque du téléphone : <%= @phone.brand %></p>
      <p>Aspect du téléphone : <%= @phone.state %></p>
      <p><%= @phone.user.username %></p>
      </div>
      <div class="desc p-3 mx-5 my-2">
      <p> description du produit : <%= @phone.description %></p>
      </div>
      <div class="desc p-3 mx-5 my-2 text-right">
      <p> <%= @phone.price %>€/jours</p>
      </div>
     <%= link_to 'Valider le paiement', new_phone_booking_path(@phone), class: "ouho btn btn-primary mt-3"  %>
    </div>

  </div>
  <% @phone.id == @last_phones_id ? @next = @first_phones_id : @next = @next_phone %>

  <%= link_to @next, class:'btn btn-primary arrow' do %>
    <p> > </p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>